import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="border-2 h-screen flex justify-center items-center gap-10 xl:text-5xl">
        <div className="border-2 rounded p-10">
          <h1>PRODUCTS</h1>
          <div className="flex flex-col gap-3 mt-4">
            <Button onClick={() => router.push("/products")}>List Products</Button>
            <Button onClick={() => router.push("/products/create")}>Create Products</Button>
          </div>
        </div>
        <div className="border-2 rounded p-10">
          <h1>ORDERS</h1>
          <div className="flex flex-col gap-3 mt-4">
            <Button onClick={() => router.push("/orders")}>List Orders</Button>
            <Button onClick={() => router.push("/orders/create")}>Create Orders</Button>
          </div>
        </div>
      </main>
    </>
  );
}
